import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:markdown/markdown.dart' as md;
import 'package:path_provider/path_provider.dart';
import 'package:super_clipboard/super_clipboard.dart';

import '../../app/app_controller.dart';
import '../../app/app_metadata.dart';
import '../../app/ui_feature_manifest.dart';
import '../../i18n/app_language.dart';
import '../../models/app_models.dart';
import '../../runtime/multi_agent_orchestrator.dart';
import '../../runtime/runtime_models.dart';
import '../../theme/app_palette.dart';
import '../../theme/app_theme.dart';
import '../../widgets/assistant_focus_panel.dart';
import '../../widgets/assistant_artifact_sidebar.dart';
import '../../widgets/desktop_workspace_scaffold.dart';
import '../../widgets/pane_resize_handle.dart';
import '../../widgets/surface_card.dart';

part 'assistant_page_main.part.dart';
part 'assistant_page_components.part.dart';
part 'assistant_page_composer_bar.part.dart';
part 'assistant_page_composer_state_helpers.part.dart';
part 'assistant_page_composer_support.part.dart';
part 'assistant_page_tooltip_labels.part.dart';
part 'assistant_page_message_widgets.part.dart';
part 'assistant_page_task_models.part.dart';
part 'assistant_page_composer_skill_models.part.dart';
part 'assistant_page_composer_skill_picker.part.dart';
part 'assistant_page_composer_clipboard.part.dart';
part 'assistant_page_components_core.part.dart';
