platform :osx, '10.15'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  append_ignored_attributes_suppression = lambda do |build_settings|
    other_cflags = build_settings['OTHER_CFLAGS'] || '$(inherited)'
    other_cxxflags = build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
    updated = false

    unless other_cflags.include?('-Wno-ignored-attributes')
      build_settings['OTHER_CFLAGS'] =
        "#{other_cflags} -Wno-ignored-attributes"
      updated = true
    end

    unless other_cxxflags.include?('-Wno-ignored-attributes')
      build_settings['OTHER_CPLUSPLUSFLAGS'] =
        "#{other_cxxflags} -Wno-ignored-attributes"
      updated = true
    end

    updated
  end

  append_deprecation_suppression = lambda do |build_settings|
    other_cflags = build_settings['OTHER_CFLAGS'] || '$(inherited)'
    other_cxxflags = build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'

    unless other_cflags.include?('-Wno-deprecated-declarations')
      build_settings['OTHER_CFLAGS'] =
        "#{other_cflags} -Wno-deprecated-declarations"
    end

    unless other_cxxflags.include?('-Wno-deprecated-declarations')
      build_settings['OTHER_CPLUSPLUSFLAGS'] =
        "#{other_cxxflags} -Wno-deprecated-declarations"
    end
  end

  append_linker_warning_suppression = lambda do |build_settings|
    other_ldflags = build_settings['OTHER_LDFLAGS'] || '$(inherited)'
    return if other_ldflags.include?('-Wl,-w')

    build_settings['OTHER_LDFLAGS'] =
      "#{other_ldflags} -Wl,-w"
  end

  normalize_system_framework_refs = lambda do |project|
    project.files.each do |file|
      next unless file.path&.include?('/System/Library/Frameworks/')
      next unless file.path.include?('Platforms/MacOSX.platform/Developer/SDKs/')

      file.path = "System/Library/Frameworks/#{File.basename(file.path)}"
      file.source_tree = 'SDKROOT'
    end
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.5'

      next unless ['mobile_scanner', 'patrol', 'CocoaAsyncSocket', 'Pods-Runner', 'Pods-RunnerTests'].include?(target.name)

      append_ignored_attributes_suppression.call(config.build_settings)
      append_deprecation_suppression.call(config.build_settings)
      append_linker_warning_suppression.call(config.build_settings)
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.targets.each do |target|
      next unless ['Runner', 'RunnerTests'].include?(target.name)

      target.build_configurations.each do |config|
        append_ignored_attributes_suppression.call(config.build_settings)
        append_linker_warning_suppression.call(config.build_settings)
      end
    end
    aggregate_target.user_project.save
  end

  normalize_system_framework_refs.call(installer.pods_project)
  installer.pods_project.save
end
